# Generated by Django 5.2.9 on 2025-12-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('utilisateur', 'Utilisateur')], default='user', max_length=20),
        ),
    ]
